services:
  - type: web
    name: forjando-milionarios
    runtime: node
    buildCommand: "rm -rf node_modules && npm install"
    startCommand: "node app.js"
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: PUPPETEER_SKIP_DOWNLOAD
        value: "true"