services:
  - type: web
    name: forjando-milionarios
    runtime: node
    buildCommand: npm install && npx puppeteer browsers install chrome
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: ADMIN_SENHA
        value: 22120929
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/.cache/puppeteer